ocsigen/ocsigen-start

src/eba_handlers.eliom
When clicking in the forgot password button,
an activation link was printed in stdout, but
no mail was sent.
This commit fixes the bug by refactoring the send_act
method.
=> eba_handlers: make forgot_password handler send a mail

src/eba_db.ml, template.distillery/PROJECT_NAME.sql
Warning: There is no guarantee for emails to be case insensitive,
but case sensitivity on emails is particularly annoying and
email servers that implement case sensitivity are extremely rare.
This patch proposes to store the original email given by the user,
but not to distinguish `A@x.x` from `a@x.x` for any query in the
database.
modified:   src/eba_db.ml
=> use case insensitive emails

template.distillery/PROJECT_NAME.eliom, template.distillery/PROJECT_NAME.sql
Column "validated" in table "emails" was missing in the SQL file.
`Eba_handlers.sign_up_handler'`
changed its name, now it's
`Eba_handlers.sign_up_handler`
=> Patch for sql file and sign_up_handler

Makefile
OCaml now issues a warning when they are missing
=> Install cmx files as well

src/os_db.ml, src/os_handlers.eliom, src/os_user.eliomi
- before: reusing an plain activation key leads to an error
- after: reusing an plain activation key just ignores the key
- justification: when an plain activation key has been used before, it
means that the account was activated. It's okay to just ignore the
key if it's used again, since the associated action cannot be done
again anyway, nor can it be undone.
- By "plain activation key", I mean a key which purpose is to activate
an account. It is the default kind of key. Other kinds of keys
include, for instance, password reset keys.
modified:   src/os_db.ml
modified:   src/os_handlers.eliom
=> fix behaviour when multiple use of plain activation key

template.distillery/Makefile.mobile
Put in comments in Makefile.mobile.
The Visual Studio solution works and was tested with a personal website. I tried manifoldJS but I can't install the APPX because it's not signed. However, the video on http://manifoldjs.com describes the entire process.
The Visual Studio solution is recommended to test and debug.
=> Add instructions to build for windows

template.distillery/Makefile.mobile, template.distillery/mobile!eliom.html.in, template.distillery/mobile!index.html.in
This PR aims to remove useless lines in the HTML files of the mobile template.
- Eliom.html.in: remove css/index.css and the div with 'app blink' because it's only index.html  which needs it. Change CSSNAME for PROJECTNAME for the css filename because it replaces with the project name.
- Makefile.mobile: remove replacement of CSSNAME by PROJECTNAME because it was the same rule
=> Remove useless lines in the HTML files of the mobile template.

src/os_current_user.eliom, src/os_userbox.eliom
**Still Ow_button.**
Ow_button is used in os_userbox and it's the last ccsigen-widgets dependency. Ow_button is used to create the button to popup the connection box.
Ow_button has some dependencies (Ow_active_set, Ow_base_widgets, etc) and I think it would take too much time to try to extract it in ocsigen-toolkit.
As I will work on the template, I will change it later. I think the template doesn't require the entire interface to Ow_button.
=> Remove Ow_log and Ow_icon dependency. 

template.distillery/Makefile.mobile
**See Important section below. PR #109 is needed !!**
When you create a new eliom project based on os.pgocaml
```
eliom-distillery -name add_platform -template os.pgocaml
```
and run
```
make add-android
```
it fails with
```
cd cordova ;\
cordova platform add android
Error: Current working directory is not a Cordova-based project.
Makefile.mobile:282: recipe for target 'cordova/platforms/android' failed
make: *** [cordova/platforms/android] Error 1
```
It is because the Cordova cli needs a Cordova based project to add the platform. A Cordova based project contains at least a `config.xml`(and other directories) which is not present when using `add-platform` because it's done when using `run-android` (with the rules `assets`). `assets` needs also `check-app-env` as dependency to replace …
=> make add-android failed because config.xml wasn't in the cordova directory

src/os_notif.eliom, src/os_notif.eliomi
split notify into two functions; add function receive_broadcast; add paramater ?broadcast to notify.
Note specifically the documentation of the ?broadcast parameter: it can only be used safely if the application does not use the optional parameter of the content generator.
=> interface to broadcast notifications to other servers

template.distillery/Makefile.mobile, template.distillery/Makefile.os, template.distillery/mobile!chcp.json.in, template.distillery/mobile!config.xml.in, template.distillery/mobile!eliom.html.in, template.distillery/mobile!index.html.in
- `chcp`: now we use the date and all files (when we did `make chcp`) goes into `update/%%DATE%%`.
- add splashes but not tested.
To do:
- Facebook.
- i18n
It will come in another PR.
This PR will have conflict with PR #132.
=> Reorganise Makefile's and mobiles files based on BS project.

src/os_current_user.eliomi, src/os_group.mli, src/os_handlers.eliomi, src/os_notif.eliomi, src/os_page.eliom, src/os_page.eliomi, src/os_session.eliomi, src/os_user.eliom, src/os_user.eliomi, src/os_userbox.eliomi
To have more readable error outputs.
I use Os_user.id instead of Os_user.userid because the module name is enough to distinguish.
See also #134 for groups.
=> Use a type Os_user.id (equivalent to int64) instead of int64 directly.

src/os_group.ml, src/os_group.mli
To have more readable error outputs. See also #133
=> Use a type Os_group.id instead of int64 directly.

template.distillery/Makefile.db, template.distillery/Makefile.options
- Use DB_SNAPSHOT instead of DBSNAPSHOT and put this variable in Makefile.options.
- Use a variable for pg_dump.
- Move pg_dump and pg_ctl at the top (because all variables must be on the top).
- Remove an useless empty new line.
=> From bs Makefile.bs: add db-snapshot rule.

src/os_msg.eliom, src/os_tips.eliom, src/os_tools.eliom, src/os_userbox.eliom, src/os_view.eliom
:gift: I heard @balat complain about these warnings and he wanted to remove it :gift:.
I agree it's better without them.
Still warnings about the cmx files.
The code is ugly but it still readable.
=> Remove warning about types inference.

src/os_view.eliom
If no `Lwt.return` the validity message remains.
=> HOTFIX in information_form: without Lwt.return, the validity state never changes.

src/os_view.eliom, src/os_view.eliomi, template.distillery/PROJECT_NAME_content.eliom
It avoids to duplicate code and it allows to use it independently of defined forms.
I think this kind of function must be in a submodule or another file. I think forms in `Os_view` must be in a submodule `Os_view.Forms`.
=> Os_view - check password function --> extract it.

src/os_db.mli, src/os_handlers.eliom, src/os_handlers.eliomi, src/os_services.eliom, src/os_services.eliomi, src/os_user.eliom, src/os_user.eliomi, src/os_userbox.eliom, src/os_view.eliom, template.distillery/PROJECT_NAME.eliom, template.distillery/PROJECT_NAME_content.eliom, template.distillery/PROJECT_NAME_handlers.eliom, template.distillery/PROJECT_NAME_handlers.eliomi
I suppose it was the previous convention naming (before the changes about services declarations).
=> Remove simple quote at the end of some handlers and services.

src/os_handlers.eliom, src/os_handlers.eliomi, template.distillery/PROJECT_NAME_mobile.eliom
`Ocsigen_handlers.restart` gains an optional `url` argument. This allows specifying the URL to jump to upon restart.
=> Ocsigen_handlers.restart ?url

src/os_user.eliom
I don't know what it is used for. It's not exported in the interface so I supposed it was only for internal uses but nothing is using it in  `Os_db`. Any explanation? Instead of an issue, I propose the PR directly if there is no reason.
=> Remove 'empty' user from Os_user

src/os_notif.eliom, src/os_notif.eliomi
- split notification type into a server type and a client type
- don't display notification for your own chat messages (works now also for multi-server set-up)
=> simplified notification interface

src/os_current_user.eliom, src/os_current_user.eliomi, template.distillery/PROJECT_NAME_content.eliom
I extract these functions with the following idea about module hierarchy:
- `Os_db` is only for low-level functions which do raw requests to database. Nothing more. No check.
- `Os_user` is a module which wraps the database functions by adding some exception or by doing some checks (if user exists, etc) before calling functions from `Os_db`. No RPC must be written here because the functions will need the userid and we don't want to have the userid client-side.
- `Os_current_user` contains functions related to the current user and the end-user must use these functions if he needs to update or remove an email. Functions defined in this file must not contained the userid in these signature but must retrieve it to call the appropriate functions in `Os_user`.
The client and server functions …
=> Move update_main_email, is_email_validated and remove_email_from_user in lib

src/os_handlers.eliomi
It causes an error during the build in Jenkins.
=> Doc: typo connect_handler.

template.distillery/Makefile.mobile
because the first `icon-%` was used instead of `icon-%2x`.
It caused bad icons generation.
=> Ios Icons generation: change order in Makefile.

template.distillery/Makefile.mobile
I forgot it in #206. Else, the build fails if we use `make run-[platform]`.
=> HOTFIX: Target icons-% before assets in run-% target

template.distillery/Makefile.mobile
Other icons are missing but I can see it for the moment (need to update Xcode I think...).
=> Makefile.mobile: Add icon-20 and icon-20@2x for iOS

.gitignore
- `.depend` is added in the template to avoid the warning `Makefile.os:275: .depend: No such file or directory`
- about `.gitignore`, I suppose it was old rules. Never this kind of files would be put in `template.distillery` directory now we use `eliom-distillery`.
=> Empty .depend file in template and update .gitignore.

Makefile
- Fix documentation generation by adding ocsigen-toolkit as dependency in eliomdoc packages
- Hide warnings to avoid to see all `...not found...`. I don't know if it's a good solution because it hides also other warnings, but which other warnings could we have?
=> Hotfix ocsigen-toolkit dependency in eliomdoc and remove warnings from eliomdoc.

src/os_lib.eliom, src/os_lib.eliomi, src/os_push_notifications.eliom, src/os_push_notifications.eliomi
It wasn't relevant to implement it before now.
I also add `string_of_stream` in the module `Os_lib` to read a response of an HTTP post request. It comes from bs.
I'm trying to test all error returned by GCM because the Google documentation is not well done. It works for the moment but I would like to test all case.
An important thing about the review it's to check if I always finalize the stream ( @vouillon ).
=> Push notifications: GCM --> FCM and parse the response.

template.distillery/Makefile.mobile
Else, res directory is copied before creating icons. It comes from a change I made some PR ago.
=> Add icons-% dependency for emulate target.

src/os_handlers.eliom
it's quite a waste of time to read those outdated comments so it's better to remove them
=> remove outdated comments

template.distillery/Makefile.mobile, template.distillery/mobile!config.xml.in
Related to https://github.com/ocsigen/ocsigen-start/issues/257.
iOS not done because I can test for the moment.
=> Remove useless icons on Android

template.distillery/Makefile.style
The condition is based on the fact that `sass -v 2> /dev/null` will return an empty string if `sass` doesn't exist. I don't know if it's portable...
By the way, the same thing must be done in `Makefile.db` I think.
=> Hotfix: check_sass wasn't working.

src/os_page.eliom, src/os_platform.eliom, src/os_platform.eliomi
**If BS uses `make_page`, it implies to modify BS because the platform will be added two times.** 
Fix #211.
I think `Os_platform` is a good idea to extract the logic of platform detection and how platforms are manipulated and detected.
Some function like `is_ios`, `is_android`, etc can be added.
This module is also useful when we want some features for a specific platform.
=> Platform module and add os-platform in the HTML tag.

README.md, opam/opam
Dev packages are installed automatically with `imagemagick` OPAM package.
On Mac OSX, `convert` is provided with homebrew package `libmagickcore-dev`.
For Ubuntu/Debian, I hope the depext install the utility.
=> Remove imagemagick instructions in the README and add it in OPAM file

template.distillery/Makefile.db
It could be useful if the log file is not in the database directory `PSQL_DIR`.
=> Remove database log file when using db-delete

template.distillery/Makefile.style
I didn't know that `postcss` existed until recently. Is it strictly needed? It seems not, so I would prefer to live with one npm thing less.
=> Downgrade postcss error to warning

template.distillery/PROJECT_NAME_mobile.eliom, template.distillery/PROJECT_NAME_userbox.eliom, template.distillery/demo_calendar.eliom, template.distillery/demo_timepicker.eliom
Some warnings are caused due to unused variable which are really used... (like `connect_form`).
=> Typo and some warnings.

opam/opam
For mac, `sass` can be installed with `sudo gem install sass` (ruby is already installed with gem). I don't know if we can install it with Homebrew.
About `sassc`, it's not mandatory as `sass` is used if `sassc` is not present.
=> OPAM depexts: ruby-sass (Ubuntu/Debian), PostgreSQL (Ubuntu/Debien/Mac OSX)

src/os_user_view.eliom, src/os_user_view.eliomi, template.distillery/sass!os.scss
Depends on https://github.com/ocsigen/ocsigen-toolkit/pull/104 and https://github.com/ocsigen/ocsigen-toolkit/pull/103.
Fix #326.
~~#335 can also be merged because we don't use it anymore. Cropping is done client-side.~~
~~Cropping server-side needs the command given in #335. It is useful if we want to save the initial image server-side for example in the database or for future cropping of the same image. Not useful for first release.~~
=> Fix avatar resizing

src/os_user_view.eliom
Some popups haven't a close icon due to this missing parameter.
=> Fix close button in bind_popup

template.distillery/Makefile.db
So that the encodings used with 'make db-init' and 'make db-create' match.
=> Set default encoding when initializing the database

src/os_handlers.eliom, template.distillery/Makefile.mobile, template.distillery/README.md, template.distillery/mobile!chcp.json.in, template.distillery/mobile!config.xml.in, template.distillery/mobile!eliom.html.in, template.distillery/mobile!index.html.in
A set of hacks that enable us to put the application under a path.
The path needs to be provided via the command line:
```
gmake emulate-android APP_REMOTE=yes APP_SERVER=http://192.168.1.1:8080 APP_PATH=/foo
```
The `APP_PATH` must be provided with the leading slash but with no trailing slash. `APP_PATH` is entirely optional. The `.conf.in` needs to be modified manually (`<site>` tag).
There is a corresponding branch for Eliom (`app-path`).
=> App under path

template.distillery/Makefile.db, template.distillery/PROJECT_NAME.conf.in, template.distillery/PROJECT_NAME.sql
We create a project-specific database for `ocsipersist`. This suppresses warnings and prevents possible conflicts between projects.
=> Use ocsipersist_%%%PROJECT_NAME%%% DB for ocsipersist

src/os_handlers.eliom, src/os_services.eliom, src/os_services.eliomi, template.distillery/PROJECT_NAME_services.eliom
We need this to redirect to the settings page after validating a new e-mail. For this, we need access to the settings service (defined in the template) from the lib. See the comments for details.
=> Use externally defined settings service in action link handler

doc/indexdoc.client, doc/indexdoc.server, src/os_user_proxy.eliomi
See http://ocsigen.org/ocsigen-start/dev/api/ for more info.
=> Some fix for API.

src/os_handlers.eliomi
See http://ocsigen.org/ocsigen-start/dev/api/client/Os_handlers.
I'm not sure it's caused by the missing empty line but I remember I resolved a similar issue like that.
=> Fix doc header for os_handlers.

src/os_comet.eliom, src/os_current_user.eliom, src/os_date.eliom, src/os_db.ml, src/os_email.eliom, src/os_handlers.eliom, src/os_msg.eliom, src/os_notif.eliom, src/os_page.eliom, src/os_session.eliom, src/os_tips.eliom, src/os_uploader.eliom, src/os_user.eliom, src/os_user_view.eliom, template.distillery/PROJECT_NAME_container.eliom, template.distillery/PROJECT_NAME_handlers.eliom, template.distillery/PROJECT_NAME_language.eliom, template.distillery/PROJECT_NAME_mobile.eliom, template.distillery/PROJECT_NAME_page.eliom, template.distillery/demo_calendar.eliom, template.distillery/demo_notif.eliom, template.distillery/demo_popup.eliom, template.distillery/demo_react.eliom, template.distillery/demo_rpc.eliom, template.distillery/demo_timepicker.eliom, template.distillery/mobile!eliom_loader.ml
Using lwt's pre-allocated threads reduce a little bit the size of the code. The gain may be very negligible here, but it means less instructions, (and less allocations?), and this optimization does not obfuscate the code so I see no reason to avoid it.
Without this patch, I have this:
```
-rw-rw-r-- 1 ju ju 723287 mars   6 00:18 /tmp/os_test/local/var/www/os_test/os_test_1874e44c161083947714d322a9696a77.js
```
And with:
```
-rw-rw-r-- 1 ju ju 723216 mars   6 00:29 /tmp/os_test/local/var/www/os_test/os_test_606d6079c9ec05cd348dc33dc2132c04.js
```
Also, even if the gain is small, it teaches the users to use these threads, which can save more space/memory in larger apps (javascript size has been reduced by 1k at besport with these replacements).
=> Lwt pre allocated threads

template.distillery/README.md
`cordova-hcp` has the following shebang:
```shell
#! /usr/bin/env node
```
However, Debian/Ubuntu (and possibly others) only have `nodejs`.
The template README now recommends a symlink as a workaround.
=> Add a note about missing node binary in template README

template.distillery/Makefile.style
This simplifies the output that the users see, and prevents a possible "sassc not found" message that may be interpreted as fatal by new users.
=> Use make conditional for sass(c) detection

src/os_email.eliom, src/os_email.eliomi, src/os_handlers.eliom
Useful for customizing the sent e-mail.
=> Os_email.send: separate url from the rest of the content

src/os_services.eliom, src/os_services.eliomi, template.distillery/PROJECT_NAME_phone_connect.eliom
... with a temporary alias to facilitate transition. I will remove the alias in a few weeks.
I wanted to use "recovery" everywhere, but I forgot to rename the service.
Also fixes template compilation.
=> Rename confirm_code_remind_service to confirm_code_recovery_service

src/os_connect_phone.eliom, src/os_current_user.eliom, src/os_handlers.eliom
Anonymous functions can confuse multi-server setups. Each server automatically produces its own incompatible names, and depending on which one responds we may call the wrong RPC.
=> Add names for all server functions

src/os_db.ml, src/os_db.mli
During initialization, one can now specify a function to be called whenever a database connection is created.
=> Os_db: add a database connection creation hook

src/os_page.eliom
The way page generation is implemented in `Eliom_client`, an `a_onload on` the `<html>` element does not work.
@dannywillems : Is there a particular reason for not using `Eliom_client.onload` here? I stuck with `a_onload` just in case.
=> fix: put a_onload on <body> instead of <html>

src/os_date.eliom, src/os_date.eliomi
It leaks memory as it uses `putenv` when switching to a different time zone. To fix that, we should push for adding `setenv` to the OCaml Unix library or provide our own binding.
The API is slightly changed: `user_tz` now returns the time zone as a string rather than as an integer offset (which was wrong anyway, as some countries, such as India, uses time offsets which are not an integral number of hours).
=> Correct time zone handling (taking into account DST)

src/os_core_db.ml, src/os_core_db.mli, src/os_db.ml, src/os_db.mli
In order to avoid any breaking change, `os_db` includes `os_core_db`.
Having `Os_core_db` is very useful in order to have side projects interacting with database of a main project based on `ocsigen-start`, and reusing some of these main project database related modules without all the dependencies it implies (i.e. eliom), copy/pasting `os_core_db.ml{,i}` into the side project, with the name of `os_db.ml{,i}`.
=> Splitted os_db into os_core_db/os_db.

Makefile.options, opam/opam, src/os_core_db.ml, src/os_core_db.mli
Depends on https://github.com/ocaml/opam-repository/pull/12396 (package PR)
The package PR has been merged. The package is now online: https://opam.ocaml.org/packages/resource-pooling/
=> rely on the resource-pooling package instead of Lwt_pool

template.distillery/Makefile.options, template.distillery/Makefile.style, template.distillery/PROJECT_NAME.eliom, template.distillery/PROJECT_NAME_mobile.eliom
One should use `Lwt_log_js` and not `Lwt_log` client-side.
Fixes #528
=> Template fixes

opam, src/os_comet.eliom, src/os_current_user.eliom, src/os_notif.eliom, src/os_session.eliom, src/os_session.eliomi
Until now the execution order of the handlers was:
1. everything registered using on_start_unconnected
2. everything registered using connected
3. everything registered using on_start_process
Now the execution order of all the handlers in these three sets is
according to the order of the registration. This ensures that handlers
registered by ocsigen-start are executed before the handlers of the
client application.
=> Os_session.on_start_(un(connected))_process: natural execution order

opam, src/os_date.eliom, src/os_date.eliomi, template.distillery/PROJECT_NAME_mobile.eliom
For that, we disable the automatic initialization of `Os_date`, which is initialized instead through this request.
=> Mobile app: make sure there is a single initial request

template.distillery/Makefile.local.example, template.distillery/Makefile.mobile, template.distillery/README.md, template.distillery/mobile!config.xml.in
Update the template's mobile build and config to allow cleartext on dev builds.
=> [template][mobile][config] Allow cleartext on dev builds

opam, src/os_core_db.ml, src/os_core_db.mli
Add the possibility to setup a wrapper function which is used each time a connection is acquired. This function can perform some actions before and/or after the connection is used
=> Os_db: connection wrapper

Makefile.options, template.distillery/Makefile.options
See [ocsigen-start doesn't compile after js_of_ocaml.3.6.0 update ](https://github.com/ocsigen/ocsigen-start/issues/589).
=> fix pkg set to js_of_ocaml-ppx_deriving_json #589

CHANGES, opam, src/os_tips.eliom, src/os_tips.eliomi
I need to animate with `Lwt` the closing of a tip
=> Os_tips: Change the type of 'onclose'

template.distillery/Makefile.i18n
This reverts commit c0a089cf86b51865a0d481de72a3b3a054c74035.
This reverts #617, fixing #619 in the process.
#617 seemed to have been badly tested. Sorry for the inconvenience, everyone
=> Revert "[template][make] fix i18n build in the template"

template.distillery/PROJECT_NAME.conf.in
It is mandatory behind a reverseproxy, and will probably always be what we want otherwise.
=> Add option <usedefaulthostname/> in template config file

.github/workflows/build.yml
opam depext doesn't seem to have an effect on MacOS.
It only prints the packages one needs to install manually.
=> [actions] fix ssl error during Github Actions compilation on macos

opam, src/os_uploader.eliom, src/os_uploader.eliomi
It involves changing the major version.
=> [cleanup] Avoid warnings 16 (`unerasable-optional-argument`)

CHANGES, opam, src/os_session.eliom, src/os_session.eliomi, template.distillery/PROJECT_NAME.opam
So that it is possible to call `Os_session.disconnect_all` outside
a request or the initialization phase of the Eliom module (see
https://ocsigen.org/eliom/dev/api/server/Eliom_state.Ext#VALfold_volatile_sub_states).
~~Depends on https://github.com/ocsigen/eliom/pull/745, waiting for the opam release of Eliom 10.0.0.~~
=> [sessions] Adjust server-side interface of `Os_session.disconnect_all`

opam
Ocsigen Start depends indirectly on Ocsigenserver 5 which needs OCaml at
least 4.08.1.
=> [opam] Fix the constraint on the OCaml version

template.distillery/Makefile.db, template.distillery/Makefile.options
To avoid warnings about the use of the deprecated command `opam config var` in opam 2.1.
=> [template] Use `opam var` instead of `opam config var`

.github/workflows/build.yml
To avoid the warning about deprecated Node.js 12 actions.  See https://github.com/ocsigen/ocsigen-start/actions/runs/4716635327.
=> [ci] Use the latest version of `actions/checkout`
