src/eba_handlers.eliom
src/eba_services.eliom
src/eba_session.eliom
src/eba_session.eliomi
src/eba_view.eliom

modified:   src/eba_handlers.eliom
modified:   src/eba_services.eliom
modified:   src/eba_session.eliom
modified:   src/eba_session.eliomi
modified:   src/eba_view.eliom

add keep me logged in feature in connection form

---

src/eba_userbox.eliomi

fix https://github.com/ocsigen/eliom-base-app/issues/37

fix https://github.com/ocsigen/eliom-base-app/issues/37

---

Makefile

modified:   Makefile
force reinstall to be done sequentially

rewrite Makefile rule "reinstall"

---

src/eba_current_user.eliom
src/eba_handlers.eliom

modified:   src/eba_current_user.eliom
modified:   src/eba_handlers.eliom

store current_user in browser local storage

---

template.distillery/mobile!config.xml.in

modified:   template.distillery/mobile!config.xml.in

mobile apps stuff: add plugin installation for cordova wkwebview

---

template.distillery/PROJECT_NAME.conf.in
template.distillery/mobile!eliom.html.in
template.distillery/mobile!index.html.in

cf. https://github.com/ocsigen/eliom/pull/309 for low-level details
modified:   template.distillery/mobile!eliom.html.in
modified:   template.distillery/mobile!index.html.in

Add option for cookie substitutes

---

template.distillery/mobile!eliom.html.in

modified:   template.distillery/mobile!eliom.html.in

add class 'eba-client-app' to html in eliom.html

---

template.distillery/mobile!config.xml.in

modified:   mobile!config.xml.in

enhance iOS app configuration settings

---

src/eba_page.eliom

modified:   src/eba_page.eliom

add platform information in the html node

---

src/eba_userbox.eliom
src/eba_userbox.eliomi

Needs https://github.com/ocsigen/ocsigen-toolkit/pull/46

Ot_picture_uploader changed its signature.

---

src/eba_userbox.eliom

This reverts commit 9a14d58816335765ba7b240b4367096cae442942.
Conflict with previous/next fix.

Revert "Fix compilation against updated Ot_picture_uploader"

---

src/eba_request_cache.eliom

modified:   src/eba_request_cache.eliom

remove wrong exception catcher

---

src/eba_handlers.eliom
src/eba_handlers.eliomi
template.distillery/PROJECT_NAME.eliom

This does not redirect to the correct page (in particular with activation links), tough...

Restart client on connection / disconnection

---

src/os_handlers.eliom

This PR restores the server-side behavior of `Eba_handlers.activation_handler` before #88. I think it doesn't interfere with the intended client-side effect of #88. 
The server-side `Eba_handlers.activation_handler` needs to redirect to the main page. If it doesn't, we stay on a URL with the activation key in it; once the user fills-in their data, the action takes us to the same URL that has a now-invalid activation key.
CC @vouillon @canonici @balat

Redirect to home page after activation

---

template.distillery/mobile!eliom.html.in
template.distillery/mobile!index.html.in

Causing errors when application starts.

Template: useless and non existing JavaScript files 

---

opam/opam
src/os_push_notifications.eliomi

add_actions tested and it's working.

Comments for os_push_notifications and add yojson in opam file.

---

template.distillery/Makefile.mobile

Makefile.mobile: Words in French

---

template.distillery/Makefile.mobile
template.distillery/Makefile.options
template.distillery/mobile!config.xml.in

In this way, the developer doesn't need to modify the config.xml.in file but only Makefile.PROJECT_NAME.
However, I think it would be better to put all variables the user can changed in a separate Makefile (like in the Makefile.local). If you agree with that, I need to change this PR by checking if the variables are already defined.

Extract some values from the config.xml.in to Makefile.mobile

---

template.distillery/README

I will work on the entire README later.

Remove camlp4 from README in the template

---

src/os_db.ml
src/os_handlers.eliom
src/os_tools.eliom
template.distillery/static!css!PROJECT_NAME.css
template.distillery/static!css!os.css

I don't know if it still some tabs... `git grep $'\t' *` outputs nothing but the makefiles.

Replace tabs.

---

template.distillery/.reserve

@vasilisp I forgot local and os_otdemo last time.
db is new since #123.

Add some reserve filenames for template: local, os_otdemo, db

---

template.distillery/Makefile.mobile
template.distillery/mobile!www!css!index.css

- Add comments in mobile/css/index.css.
- Makefile.mobile: remove the index.js file generated by default by Cordova because it's not anymore used in eliom.html or index.html.

Comments in mobile/css/index.css and remove generated index.js.

---

template.distillery/Makefile.mobile

+ remove eliom_loader related files generated during the compilation in the mobile-clean rule.

Add comments and reorganize Makefile.mobile to be more readable

---

template.distillery/PROJECT_NAME_base.eliom

It removes a warning during template compilation.

Remove int_of_port which is never used.

---

LICENSE

Comes from COPYING eliom file. @balat

LICENSE: change LGPL v3 --> v2.1 with linking exceptions.

---

template.distillery/Makefile.mobile
template.distillery/Makefile.options
template.distillery/mobile!config.xml.in

It's [this plugin](https://github.com/phonegap/phonegap-plugin-push).
@pwbs

phonegap-push-plugin in config.xml

---

template.distillery/mobile!eliom_loader.ml
template.distillery/mobile!index.html.in
template.distillery/mobile!www!css!index.css

- Eliom_loader:
- add comments to explain how it works.
- reorganize some evaluations.
- change the theme color (blue) to light theme color (#12B0E6).
- add blink when push on retry button.
- index.html
- index.css
- style for the retry button. Here the new style:

Eliom_loader.ml + readd blink class in index.html

---

src/os_handlers.eliom
src/os_user.eliom
src/os_user.eliomi

As it shadows existing OS_user.update function...

Rename back Os_user.update to Os_user.update'

---

src/os_db.ml
src/os_db.mli
src/os_handlers.eliom
src/os_user.eliom
src/os_user.eliomi
template.distillery/PROJECT_NAME_content.eliom

I think it makes more sense.
**Since it's changed in the template, I suppose it must be changed in BS.**

get_email_validated --> is_email_validated

---

template.distillery/Makefile.os

Add some ocsigenserver running information

---

template.distillery/mobile!config.xml.in

I tested it *on Android*. It's OK.

Update phonegap-plugin-push to 1.8.2

---

template.distillery/Makefile.mobile

- generate icons only for the current built platform.
- rule for cleaning icons.

Template mobile:

---

src/os_date.eliom
src/os_user_proxy.eliom

See:
https://github.com/ocsigen/ocsigen-toolkit/pull/79
https://github.com/ocsigen/ocsigen-widgets/pull/14

Do not use client-side server_function

---

.jenkins.sh
Makefile
src/os_push_notifications.eliomi
src/os_types.eliomi

See #165.
@Drup It must fix the continuous integration. I can generate the doc with `make doc` in local so I suppose it's ok.

Fix continuous integration

---

template.distillery/mobile!config.xml.in

Ok on Android.
See [changelog](https://github.com/nordnet/cordova-hot-code-push/blob/master/CHANGELOG.md)
@pwbs Could you test it on iOS?

Update hot code push to 1.5.1

---

src/os_group.ml
src/os_group.mli

It was an old PR #190 I closed by removing the branch...

Fix description of [group_of_name] in Os_group module

---

src/os_db.ml
src/os_handlers.eliom

fix: security issue in account creation (regarding emails)

---

src/os_db.ml
src/os_db.mli
src/os_user.eliom
src/os_user.eliomi
template.distillery/PROJECT_NAME_handlers.eliom

If it's ok, BS must be changed first @balat.

Userid as first parameter for consistency.

---

src/os_db.ml
template.distillery/.eliomignore
template.distillery/Makefile.db
template.distillery/Makefile.options
template.distillery/PROJECT_NAME.sql
template.distillery/README
template.distillery/upgrade.sql

I can't test it because the template is in progress but it compiles...

Prefix tables with os_

---

src/os_db.ml

fix inverted condition for email availability

---

template.distillery/Makefile.mobile

Related to https://github.com/ocsigen/tutorial/pull/50

Remove instruction for building mobile apps from Makefile.mobile

---

template.distillery/Makefile.options
template.distillery/Makefile.style

It fixes https://github.com/ocsigen/ocsigen-start/issues/218.

Remove cp -n. -n means it won't never rewrite files.

---

src/os_userbox.eliom

Remove warnings about close

---

template.distillery/Makefile.style

Resolve issue about sed -i

---

template.distillery/Makefile.mobile

when building for multiple platforms.
Fix #217

Mobile: resolve issue about resources directory

---

template.distillery/Makefile.style

Error when SASS is not available.

---

src/os_current_user.eliom
src/os_current_user.eliomi
src/os_db.ml
src/os_db.mli
src/os_group.ml
src/os_group.mli
src/os_handlers.eliom
src/os_handlers.eliomi
src/os_notif.eliom
src/os_notif.eliomi
src/os_page.eliom
src/os_page.eliomi
src/os_session.eliomi
src/os_types.eliom
src/os_types.eliomi
src/os_user.eliom
src/os_user.eliomi
src/os_user_proxy.eliom
src/os_user_proxy.eliomi
src/os_userbox.eliomi
src/os_view.eliomi
template.distillery/PROJECT_NAME_container.eliomi
template.distillery/PROJECT_NAME_handlers.eliom
template.distillery/PROJECT_NAME_handlers.eliomi
template.distillery/PROJECT_NAME_page.eliomi
template.distillery/PROJECT_NAME_userbox.eliomi

Os_types: use submodule for group, user and activation link key.

---

template.distillery/Makefile.db

Hotfix: check_psql wasn't working.

---

src/os_db.ml
src/os_db.mli
src/os_handlers.eliom
src/os_handlers.eliomi
template.distillery/PROJECT_NAME_handlers.eliom

change behavior for already used activation keys

---

template.distillery/Makefile.mobile

URGENT: Missing CORDOVA_RES_PATH variable.

---

template.distillery/.eliomignore

Discussion here: https://github.com/ocsigen/eliom/pull/374

Ignore .eliomreserve (old .reserve)

---

template.distillery/.gitignore

I don't know if `.ocp-indent` must be ignored or not.

Update gitignore template

---

template.distillery/Makefile.mobile

No error if cordova/res exists

---

src/os_email.eliom
template.distillery/PROJECT_NAME_base.eliom

stop using an absolute path for sendmail.

---

template.distillery/.eliomignore
template.distillery/.eliomverbatim

Nothing but renaming. See ocsigen/eliom#418.
CC @balat

Add .eliomverbatim file to template

---

src/os_handlers.eliom

https://github.com/ocsigen/eliom/commit/0a044976e79cbef97eb2cf3edeb2945f0dd1a34d

compatibility with eliom

---

.travis.yml

Must work: https://travis-ci.org/dannywillems/ocsigen-start/builds/178786015

Fix PostgreSQL Travis

---

.travis.yml

Travis: stop PostgreSQL with service

---

template.distillery/README.md

- add NVM solution
- remove useless comment (through USB)
- add usage information for Makefile.local

README template

---

src/os_notif.eliom
src/os_notif.eliomi

rewrite of Os_notif as specialisation of Eliom_notif

---

template.distillery/demo_popup.eliom

Missing close button in demo popup

---

template.distillery/Makefile.style

It took me some time to realize the corresponding NPM package was `postcss-cli`...

Add NPM command to warning about postcss

---

template.distillery/static!defaultcss!os.css

I forgot to use `make generate-css` in #341 to update the corresponding CSS file.

Update the template CSS.

---

Makefile.options
opam/opam
src/os_uploader.eliom
src/os_uploader.eliomi
src/os_user_view.eliom
src/os_user_view.eliomi
template.distillery/PROJECT_NAME.eliom
template.distillery/PROJECT_NAME_settings.eliom

Remove ImageMagick binding dependency and use convert command directly

---

template.distillery/mobile!config.xml.in

add geolocation plugin

---

template.distillery/PROJECT_NAME.eliom
template.distillery/PROJECT_NAME_handlers.eliom
template.distillery/PROJECT_NAME_handlers.eliomi

Redirect to reload_action after setting password

---

template.distillery/Makefile.os

Template: fix compilation with DEBUG=no

---

src/os_db.ml
src/os_db.mli
src/os_group.ml
src/os_group.mli
src/os_session.eliom

modified:   src/os_db.ml
modified:   src/os_db.mli
modified:   src/os_group.ml
modified:   src/os_group.mli
modified:   src/os_session.eliom

going towards enhancing performance in database connection usage

---

README.md

Add links to demo and remove an useless section.
Add also a link to the manual (as asked on Twitter).

Update README for instructions to start.

---

tools/sort_deps.ml

sort_deps.ml: print dependency loop.

---

src/os_db.ml

Os_db: fixed IO int endianess.

---

src/os_comet.eliom

(fixes restarts when app is running in some iframes)

Disabling restart after comet failure when cookies are disabled

---

template.distillery/demo_calendar.eliom

Maybe it doesn't belong there, I don't know...

Explain a beginner's mistake about "shared signals"

---

0.99/api/index.html
1.0/api/index.html
1.1.0/api/index.html

Need for http://ocsigen.org/ocsigen-start/1.1.0/api/ to work.

add main page for api doc

---

template.distillery/assets!PROJECT_NAME_i18n.tsv
template.distillery/demo_cache.eliom
template.distillery/demo_react.eliom

i18n fixes

---

template.distillery/Makefile.db

Fix detection of pg_ctl on Debian

---

src/os_db.ml
src/os_db.mli
src/os_fcm_notif.eliom
src/os_fcm_notif.eliomi
src/os_group.ml
src/os_group.mli
src/os_session.eliom
src/os_session.eliomi
src/os_tips.eliomi
src/os_uploader.eliomi
src/os_user.eliom
src/os_user.eliomi
template.distillery/Makefile.mobile
template.distillery/Makefile.options
template.distillery/PROJECT_NAME_handlers.eliomi
template.distillery/demo.eliom
template.distillery/demo_notif.eliom
template.distillery/demo_pagetransition.eliom
template.distillery/mobile!www!css!index.css

Typos found with https://github.com/codespell-project/codespell

Fixing typos

---

Makefile.options
opam

We are planning to remove any dependency on ocamlnet from eliom and ocsigenserver

Add dependency on ocamlnet/netstring (for sending mails)

---

opam
src/os_connect_phone.eliom
src/os_connect_phone.eliomi
src/os_db.ml
src/os_db.mli
src/os_handlers.eliom
src/os_user.eliom
src/os_user.eliomi
src/os_user_view.eliom
template.distillery/assets!PROJECT_NAME_i18n.tsv

(Wrong password, password not set, or no such user)

User connection: more detailed explanation of failed login

---

.travis.yml

Resolves #561. See text in that issue.

Travis: reduce number of build rows

---

opam
template.distillery/mobile!eliom_loader.ml

Make 'Eliom_loader' compile

---

opam
src/os_comet.eliom

[comet] Use React-based API

---

template.distillery/demo_notif.eliom

Weird programming style and
was buggy when page generated on client.

[Demo] Fix demo_notif

---

template.distillery/Makefile.i18n

Fixes the i18n build of the template.
Thanks to @Zzull for reporting the error

[template][make] fix i18n build in the template

---

opam
src/os_comet.eliom
src/os_session.eliom
src/os_session.eliomi

Merge https://github.com/ocsigen/eliom/pull/671 first

Update for Eliom 7

---

template.distillery/README.md

Since the tutorial about the android installation did not work very well, here is the new version of the README for the template.

[template] README.md correction for ANDROID mobile installation

---

.github/workflows/build.yml
opam
template.distillery/PROJECT_NAME.conf.in
template.distillery/PROJECT_NAME.opam

Depends on: https://github.com/ocsigen/ocsigen-start/pull/635

compatibility of template distillery with outsourced ocsipersist

---

src/os_db.ml
src/os_db.ppx.ml

It seems the activation link is sometimes opened several times (once in a navigator and once in the app?) on some devices. So that it can still be use in this case, we do not expire it once away but let it active for 20 seconds.

activation links: add short grace period before expiration

---

opam
src/os_db.ml

Completes https://github.com/ocsigen/ocsigen-start/pull/650.

[groups] Rebuild `src/os_db.ml` to reflect changes in `src/os_db.ppx.ml`

---

template.distillery/Makefile.style

Hello,
I detect an error in Makefile.style that blocked sass generation.

Fix SASS generation in Makefile.style
